loja/urls.py
from django import urls
from django.urls import path
from loja import views


urlpatterns = [


    #Home
    path('', views.index, name='index'),


    # #Products
    path('category-list/', views.category_list, name='category-list'),
    path('product-list/', views.product_list, name='product-list'),
    path('marca-list/', views.marca_list, name='marca-list'),
    path('size-list/', views.size_list, name='size-list'),

    # path('category/<int:category_id>/', views.category, name='category'),
    # path('product/<int:product_id>/', views.product, name='product'),
    # path('cart/', views.cart, name='cart'),
    # path('checkout/', views.checkout, name='checkout'),
    # path('order/', views.order, name='order'),
    # path('order_complete/', views.order_complete, name='order_complete'),
    #
    # #Login
    # path('login/', views.login, name='login'),
    # path('logout/', views.logout, name='logout'),
    # path('register/', views.register, name='register'),
    #
    #
    #
    # # Profile
    #
    # path('profile/', views.profile, name='profile'),
    # path('profile_edit/', views.profile_edit, name='profile_edit'),
    # path('profile_password/', views.profile_password, name='profile_password'),
    # path('profile_address/', views.profile_address, name='profile_address'),
    # path('profile_address_edit/<int:address_id>/', views.profile_address_edit, name='profile_address_edit'),
    # path('profile_address_delete/<int:address_id>/', views.profile_address_delete, name='profile_address_delete'),
    # path('profile_address_add/', views.profile_address_add, name='profile_address_add'),

    ]

myFood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('loja.urls')),
]

loja/models.py
from django.db import models


# Create your models here.

class Banner(models.Model):
    img = models.CharField(max_length=200)
    alt_text = models.CharField(max_length=200, blank=True, null=True)


class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category', blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'category'


class Marca(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Size(models.Model):
    title = models.CharField(max_length=100,)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=400)
    image = models.ImageField(upload_to='product', blank=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.product.title

    class Meta:
        db_table = 'product_attribute'

loja/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def category_list(request):
    return render(request, 'category_list.html')

def product_list(request):
    return render(request, 'product_list.html')

def marca_list(request):
    return render(request, 'marca_list.html')

def size_list(request):
    return render(request, 'size_list.html')

loja/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>My_Food</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
	<!-- CustomJs -->
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-success">
		<div class="container">
		  <a class="navbar-brand" href="{% url "index" %}">Loja Django</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		  	<form class="form-inline my-2 my-lg-0" action="/search">
		      <div class="input-group">
				  <input name="q" type="text" class="form-control" placeholder="Pesquisar" />
				  <div class="input-group-append">
				    <button class="btn btn-dark" type="submit" id="button-addon2">Pesquisar</button>
				  </div>
				</div>
		    </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url "index" %}">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category-list'%}">Categorias</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'marca-list'%}"">Marcas</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href=""><i class="fa fa-shopping-cart"></i> Carrinho (<span class="cart-list"></span>)</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fa fa-user"></i> Minha Conta
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

		        	<a class="dropdown-item" href="">Painel</a>
		        	<a class="dropdown-item" href="">Sair</a>

	        		<a class="dropdown-item" href="">Login</a>
		          <a class="dropdown-item" href="">Cadastrar</a>

		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>

    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container" >
    <div class="row">
        <div class="col-12 col-md">
        <a href="{% url "index" %}">Loja Django 2022</a>
        <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Produtos Legais</a></li>
            <li><a class="text-muted" href="#">Recurso Aleatórios</a></li>
            <li><a class="text-muted" href="#">Recursos em Equipe</a></li>
            <li><a class="text-muted" href="#">Produtos Para Desenvolvedores</a></li>
            <li><a class="text-muted" href="#">Outros</a></li>
            <li><a class="text-muted" href="#">Última Oportunidade</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Recursos</a></li>
            <li><a class="text-muted" href="#">Nome Do Recurso</a></li>
            <li><a class="text-muted" href="#">Outro Recurso</a></li>
            <li><a class="text-muted" href="#">Recurso Final</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Sobre</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Equipe</a></li>
            <li><a class="text-muted" href="#">Localizações</a></li>
            <li><a class="text-muted" href="#">Privacidade</a></li>
            <li><a class="text-muted" href="#">Termos</a></li>
        </ul>
        </div>
    </div>
    </footer>
</body>
</html>

loja/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Categorias</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href=""><img src="/media/{{cat.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

loja/templates/filters.html
{% load static %}
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
			<h3 class="mb-4 border-bottom pb-1">Filtros</h3>
			
			<div class="card mb-4">
				<h6 class="card-header">Preco</h6>
				<div class="list-group list-group-flush">
					<li class="list-group-item">
						<input type="range" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} id="rangeInput" oninput="maxPrice.value=this.value" />
						<p>{{minMaxPrice.price__min}}-{{minMaxPrice.price__max}}</p>
					</li>
					<li class="list-group-item">
						Maximo: <input type="number" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" id="maxPrice" />
						<button id="priceFilterBtn" class="btn btn-info btn-sm mt-1">Filtros</button>
					</li>
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Cores</h6>
				<div class="list-group list-group-flush">
					{% for color in colors %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="color" value="{{color.color__id}}" type="checkbox" />&nbsp;
						<button class="btn" style="background-color: {{color.color__color_code}}; margin-top: -5px;"></button>
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Categorias</h6>
				<div class="list-group list-group-flush">
					{% for cat in cats %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="category" value="{{cat.category__id}}" type="checkbox" />&nbsp;
						{{cat.category__title}}
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Marcas</h6>
				<div class="list-group list-group-flush">
					{% for marca in marcas %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="marca" value="{{marca.marca__id}}" type="checkbox" />&nbsp;
						{{marca.marca__title}}
					</li>
					{% endfor %}
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Tamanhos</h6>
				<div class="list-group list-group-flush">
					{% for size in sizes %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="size" value="{{size.size__id}}" type="checkbox" />&nbsp;
						{{size.size__title}}
					</li>
					{% endfor %}
				</div>
			</div>

loja/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
   
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/media/images/banners/banner1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner3.jpg' %}" class="d-block w-100" alt="...">
    </div>
   
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Proximo</span>
  </a>
</div>
</div>
<main class="container my-4">
	
	<h3 class="my-4 border-bottom pb-1">Produtos Em Destaques</h3>
	<div class="row">
   
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/images/sapatos.jpg' %}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href=""></a>Comidas</h5>
          <h6>R$ <span class=""></span></h6>
			  </div>
			  <div class="card-footer">

          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
         
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
         
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
       
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
   
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">Todos Produtos <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}

loja/templates/marca_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Marcas</h3>
	<div class="row">
		{% if data %}
			{% for marca in data %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href=""><img src="/media/{{marca.image}}" class="card-img-top" alt="{{marca.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="#">{{marca.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

loja/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			
			<h3 class="mb-4 border-bottom pb-1">
				Produtos
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Carregando...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="</span></h6>
					  </div>
					  	<div class="card-footer">
				         
							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Carregar + <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>My_Food</title>
	<!-- Font Awesome -->
	<link rel="stylesheet" type="text/css" href="{% static 'fontawesome-free/css/all.min.css' %}" />
	<!-- Bootstrap 4 CSS -->
	<link rel="stylesheet" type="text/css" href="{% static 'bs4/bootstrap.min.css' %}" />
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script type="text/javascript" src="{% static 'bs4/bootstrap.min.js' %}"></script>
	<!-- CustomJs -->
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-success">
		<div class="container">
		  <a class="navbar-brand" href="/loja/static">Loja Django</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		  	<form class="form-inline my-2 my-lg-0" action="/search">
		      <div class="input-group">
				  <input name="q" type="text" class="form-control" placeholder="Pesquisar" />
				  <div class="input-group-append">
				    <button class="btn btn-dark" type="submit" id="button-addon2">Pesquisar</button>
				  </div>
				</div>
		    </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/loja/static">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'category-list'%}">Categorias</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'marca-list'%}"">Marcas</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href=""><i class="fa fa-shopping-cart"></i> Carrinho (<span class="cart-list"></span>)</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fa fa-user"></i> Minha Conta
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
		      
		        	<a class="dropdown-item" href="">Painel</a>
		        	<a class="dropdown-item" href="">Sair</a>
	        	
	        		<a class="dropdown-item" href="">Login</a>
		          <a class="dropdown-item" href="">Cadastrar</a>
		    
		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>
    
    {% block content %}
    {% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
        <div class="col-12 col-md">
        <a href="#">Loja Django 2022</a>
        <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Produtos Legais</a></li>
            <li><a class="text-muted" href="#">Recurso Aleatórios</a></li>
            <li><a class="text-muted" href="#">Recursos em Equipe</a></li>
            <li><a class="text-muted" href="#">Produtos Para Desenvolvedores</a></li>
            <li><a class="text-muted" href="#">Outros</a></li>
            <li><a class="text-muted" href="#">Última Oportunidade</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Recursos</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Recursos</a></li>
            <li><a class="text-muted" href="#">Nome Do Recurso</a></li>
            <li><a class="text-muted" href="#">Outro Recurso</a></li>
            <li><a class="text-muted" href="#">Recurso Final</a></li>
        </ul>
        </div>
        <div class="col-6 col-md">
        <h5>Sobre</h5>
        <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Equipe</a></li>
            <li><a class="text-muted" href="#">Localizações</a></li>
            <li><a class="text-muted" href="#">Privacidade</a></li>
            <li><a class="text-muted" href="#">Termos</a></li>
        </ul>
        </div>
    </div>
    </footer>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
   
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/media/images/banners/banner1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner2.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner3.jpg' %}" class="d-block w-100" alt="...">
    </div>
   
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Proximo</span>
  </a>
</div>
</div>
<main class="container my-4">
	
	<h3 class="my-4 border-bottom pb-1">Produtos Em Destaques</h3>
	<div class="row">
   
		<div class="col-md-3 mb-4">
			<div class="card shadow">
			  <a href="/product/{{product.slug}}/{{product.id}}"><img src="{% static '/media/images/sapatos.jpg' %}" class="card-img-top" alt="{{product.title}}"></a>
			  <div class="card-body">
			    <h5 class="card-text"><a href=""></a>Sapatos</h5>
          <h6>R$ <span class=""></span></h6>
			  </div>
			  <div class="card-footer">
         
          <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
          <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
          <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
          <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
			  	<button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>
         
			  	<button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>
         
          <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>
       
			  	<span class="float-right">
			  		4.5/5
			  		<i class="fa fa-star text-warning"></i>
			  	</span>
			  </div>
			</div>
		</div>
   
	</div>
	<p class="my-4 text-center"><a href="{% url 'product-list' %}" class="btn btn-dark btn-sm">Todos Produtos <i class="fa fa-long-arrow-alt-right"></i></a></p>
</main>
{% endblock %}